# Generated by Django 4.1 on 2022-09-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('serialno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('auther', models.CharField(max_length=150)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
