# Generated by Django 4.1 on 2022-09-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
